data:
  env: dev
  user:
    userName: root
    password: AQAaKfPqNfAjQz+WtV7GAa2h6KWw3J1ZxgB5JDEhj5ucS1vnh+t5ZUOjfmPaNjGRmfLNvdRxMZ6cwwDEmRrzLmy9ClrO7TvwzZ/F+UTcFK6zD6ToP69t61At0J1y5wf13Of8/3cq5wWKlzLgx5hDT8mw/rCy4WuSOsYysxpXEfiFlzeSlbx8sj5bdTtbZ0UFCG0mbBCgsAvEdaNfCMBFgyecbJRsaJ7XzYjCmmL7vIHHlYnJsM5fm5ZtnlNS9X1UqxtgNZ7ufySBhBdsqxcEca1WPOlq2i9M1mTmfopOpEjBzqbLO/7eoriAFWSlbiGUIYHSJ4bx+iHZca1mHWuiEFXf7xZjUKsfY3Xw/bujCVYeIgAFFBjoy/Okc2xrXDNBR/I=
